version: 1.0.{build}
cache: C:\Users\appveyor\Downloads -> appveyor.yml
environment:
  ANTCC_INSTALLER_URL: https://github.com/SoftwareAG/sagdevops-antcc/releases/download/v10.3-rc13/
  ANTCC_VERSION: 10.3-stable
  ANTCC_DISTRO: antcc-nojava
install:
- ps: bootstrap/install.ps1
build_script:
- cmd: antcc help
deploy: off
