version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: choco install ant
cache: C:\Users\appveyor\Downloads
build_script:
- cmd: >-
    ant client

    ant boot -Daccept.license=true
deploy: off