version: 1.0.{build}
cache: C:\Users\appveyor\Downloads -> appveyor.yml
environment:
  CC_INSTALLER_URL: ANTCC_INSTALLER_URL=https://github.com/SoftwareAG/sagdevops-antcc/releases/download/v10.4
  ANTCC_VERSION: 10.4-stable
install:
- ps: bootstrap/install.ps1
build_script:
- cmd: antcc help
deploy: off
